import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function LoginLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <div className="w-10 h-10 bg-red-800" />
      {children}
    </div>
  )
}
