import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { Providers } from '@/app/providers'
import { Button } from '@/components/atoms/Button'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' relative'}>
        <Providers>
          <Link className="absolute top-0 right-0" href="/api/auth/signout">
            <Button label="Wyloguj" />
          </Link>
          {children}
        </Providers>
      </body>
    </html>
  )
}
