import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { Providers } from '@/app/providers'
import { Button } from '@/components/atoms/Button'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className + ' relative'}>
        <Providers>
          <div className="absolute top-0 right-0 flex gap-1">
            <Link href="/">
              <Button label="Home" />
            </Link>
            <Link href="/temp/chat">
              <Button label="Chat" />
            </Link>
            <Link href="/auth/register">
              <Button label="Rejestracja" />
            </Link>
            <Link href="/api/auth/signout">
              <Button label="Wyloguj" />
            </Link>
          </div>
          {children}
        </Providers>
      </body>
    </html>
  )
}
