/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Tower(props) {
  const { nodes, materials } = useGLTF('./models/1.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 8.5, 0]} rotation={[0, 0, Math.PI]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/1.glb')
